import JSZip from 'jszip';

export async function downloadProjectZip(files, appName, isMobile = false) {
  const zip = new JSZip();
  const safeName = appName.toLowerCase().replace(/[^a-z0-9]/g, '-');

  // Add standard files
  zip.file('src/App.jsx', files['App.jsx'] || '');
  zip.file('src/index.css', files['styles.css'] || '');
  
  // HTML index
  const htmlContent = `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${appName}</title>
  </head>
  <body class="bg-slate-950 text-slate-100">
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>`;
  zip.file('index.html', htmlContent);

  // Main React entry
  const mainJsx = `import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App.jsx';
import './index.css';

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);`;
  zip.file('src/main.jsx', mainJsx);

  // Package.json
  const packageJson = `{
  "name": "${safeName}",
  "private": true,
  "version": "1.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "lucide-react": "^0.344.0"
    ${isMobile ? ',\n    "@capacitor/core": "^5.7.0",\n    "@capacitor/android": "^5.7.0"' : ''}
  },
  "devDependencies": {
    "@types/react": "^18.2.56",
    "@types/react-dom": "^18.2.19",
    "@vitejs/plugin-react": "^4.2.1",
    "autoprefixer": "^10.4.18",
    "postcss": "^8.4.35",
    "tailwindcss": "^3.4.1",
    "vite": "^5.1.4"
    ${isMobile ? ',\n    "@capacitor/cli": "^5.7.0"' : ''}
  }
}`;
  zip.file('package.json', packageJson);

  // Tailwind config files
  const tailwindConfig = `/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}`;
  zip.file('tailwind.config.js', tailwindConfig);

  const postcssConfig = `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}`;
  zip.file('postcss.config.js', postcssConfig);

  const viteConfig = `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
});`;
  zip.file('vite.config.js', viteConfig);

  // Capacitor settings for mobile apps
  if (isMobile) {
    const capConfig = `{
  "appId": "com.lumina.${safeName.replace(/-/g, '')}",
  "appName": "${appName}",
  "webDir": "dist",
  "server": {
    "androidScheme": "https"
  }
}`;
    zip.file('capacitor.config.json', capConfig);
  }

  // Instructions README
  const readmeContent = `# ${appName}

Generated by Lumina Studio.

## Local Development

1. Install dependencies:
   \`\`\`bash
   npm install
   \`\`\`

2. Start the local dev server:
   \`\`\`bash
   npm run dev
   \`\`\`

3. Build for production:
   \`\`\`bash
   npm run build
   \`\`\`

${isMobile ? `## Native Mobile Deployment (Capacitor)

This application is ready to run as a native mobile app.

1. Build the production web bundle:
   \`\`\`bash
   npm run build
   \`\`\`

2. Add the Android platform (or ios):
   \`\`\`bash
   npx cap add android
   \`\`\`

3. Sync web assets to Capacitor:
   \`\`\`bash
   npx cap sync
   \`\`\`

4. Open the project in Android Studio / Xcode to run it:
   \`\`\`bash
   npx cap open android
   \`\`\`
` : ''}`;
  zip.file('README.md', readmeContent);

  // Generate ZIP blob and trigger download
  const content = await zip.generateAsync({ type: 'blob' });
  const element = document.createElement('a');
  element.href = URL.createObjectURL(content);
  element.download = `${safeName}-project.zip`;
  document.body.appendChild(element);
  element.click();
  document.body.removeChild(element);
}
